//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR___Manager.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string EmploymentContractNumber { get; set; }
        public Nullable<System.DateTime> DateOfDismissal { get; set; }
        public Nullable<int> UserInfoID { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
